#!/usr/bin/env python3

import metrics_refbox.metrics_refbox_gui
import rospy

if __name__ == '__main__':
    rospy.init_node('metrics_refbox', anonymous=True)
    metrics_refbox.metrics_refbox_gui.main()
